# Reference on this file: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Lint, build and test
on:
  pull_request:
jobs:
  build:
    name: Lint, build and test
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/build-typescript-project.yml@v1
